version: 1

update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "dependabot/dependabot-core"
